### ISSUE TITLE
ブランチ整理を行う

### ISSUE THREAD

**Issue by Murayu0225** [Murayu0225/youtube-dev#2]
## 改善詳細 / Details of Improvement
- mainブランチの状況をなくす。
- developブランチを作成してコントリビューターの方々が貢献・PR作成しやすくする。

## スクリーンショット / Screenshot

N.

## 期待する見せ方・挙動 / Expected behavior
N.

**Comment by assistant-app-dev** [comment]
developブランチとの自動同期は、コンフリクトするのでやめました。
developブランチの作成はできているのでクローズします。
